/*
  Warnings:

  - You are about to alter the column `id` on the `users` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_users" (
    "id" INT2 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "email" STRING NOT NULL,
    "hash" STRING NOT NULL,
    "firstName" STRING,
    "lastName" STRING,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
DROP INDEX "users_email_key";
INSERT INTO "_prisma_new_users" ("createdAt","email","firstName","hash","id","lastName","updatedAt") SELECT "createdAt","email","firstName","hash","id","lastName","updatedAt" FROM "users";
DROP TABLE "users" CASCADE;
ALTER TABLE "_prisma_new_users" RENAME TO "users";
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
