-- CreateTable
CREATE TABLE "courses" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "user_id" INT4 NOT NULL,
    "category_id" INT4 NOT NULL,
    "audience_id" INT4 NOT NULL,
    "topic_ids" INT4[],
    "duration_in_hours" INT4 NOT NULL,
    "duration_lesson_in_minutes" INT4 NOT NULL,
    "description" STRING NOT NULL,
    "accepted_lesson_template_ids" INT4[],
    "lesson_card_template_id" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "objective" STRING NOT NULL,

    CONSTRAINT "courses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Audience" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "Audience_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Tone" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "Tone_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Topic" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "Topic_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LessonTemplate" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "LessonTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LessonCardTemplate" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "LessonCardTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Language" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "Language_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "courses" ADD CONSTRAINT "courses_lesson_card_template_id_fkey" FOREIGN KEY ("lesson_card_template_id") REFERENCES "LessonCardTemplate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "courses" ADD CONSTRAINT "courses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
